### ISSUE TITLE
Episode Counting Bug

### ISSUE THREAD

**Issue by Skepller** [pystardust/ani-cli#1375]
**Metadata**
Version: 4.8.10
OS: Pop!_OS 22.04
Shell: bash 5.1.16
Anime: Solo Leveling (Ore dake Level Up na Ken)

**Describe the bug**
When displaying the episode count for some animes, like Solo Leleving, something is broken.
When being displayed on a search or history list, it appears as "Ore dake Level Up na Ken (**7.7.7.7.5** episodes)".
If you list the episodes, it shows 1 to 12 and then "7.5" as the last episode, instead of 13.

Looking at my history list, Jujutsu Kaisen 2nd Season also seems affected (appears as "5.5 episodes").

Not every anime is impacted, the other 4 on my history seem normal.

**Steps To Reproduce**

1. Run `ani-cli solo leveling`
2. Look at the count of the last episode

**Expected behavior**
Display episode count correctly.

**Screenshots**
![image](https://github.com/pystardust/ani-cli/assets/12860192/0c388813-5c80-4dfb-8028-298a2fa143a5)
![image](https://github.com/pystardust/ani-cli/assets/12860192/61c05005-1dcb-48c7-b4b4-4f89c61d5b4c)

**Comment by Skepller** [comment]
I don't know if it was just after some time or if it has something to do with the number of episodes you watch, but now it got worse:

"**7.7.7.7.7.7.7.7.5** Episodes" lmao
![image](https://github.com/pystardust/ani-cli/assets/12860192/1be5ccc0-5b14-4dd9-a733-27c3fa50f567)

**Comment by port19x** [comment]
There are `.5` episodes in some anime, but this seems strange.
We should verify if this is just allanime trolling or an actual bug in our code

**Comment by 71zenith** [comment]
I cannot recreate this in any capacity

**Comment by port19x** [comment]
Then we'll close this in a week unless we get further updates by @Skepller

**Comment by Skepller** [comment]
I can easily recreate it and the script is up-to-date, perhaps some dependency in a different version?

- `ani-cli -D`
- `ani-cli solo leveling` > clicked episode 2
- `ani-cli edgerunners` > clicked episode 3
- `ani-cli -c` shows as expected:
![image](https://github.com/user-attachments/assets/182a2e4e-aa53-4688-82d2-14315d366f46)

This is some of what I could find in regard to dependencies:
```
  grep:
    Installed: 3.7-1build1
  sed:
    Installed: 4.8-1ubuntu2
  curl:
    Installed: 7.81.0-1ubuntu1.16
  mpv:
    Installed: 0.34.1-1ubuntu3
  ffmpeg:
    Installed: 7:4.4.2-0ubuntu0.22.04.1
  fzf:
    Installed: 0.29.0-1
  patch:
    Installed: 2.7.6-7build2
```
